import { DailyActivity, ReminderItem, CognitiveGame, MemoryItem, CaregiverAlert, ContactItem, PatientProfile, LanguageCode } from '../types';

export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    languageName: "English",
    appName: "SANGPA",
    tagline: "Small steps. Big moments.",
    caregiverBtn: "I am a caregiver",
    patientBtn: "I am here for care and activities",
    listenInstructions: "Listen to instructions",
    openingInstruction: "Welcome to SANGPA! If you are here for daily care, gentle exercises, and fun memory games, please press the large green button below. If you are a family caregiver, press the white caregiver button. I am right here with you!",
    greeting: "Namaste, Kamala Dadi",
    whatToDo: "What would you like to do?",
    nextActivity: "Next Activity",
    drinkWater: "Drink water at 10:00 AM",
    calmMessage: "You are doing well today. Let's take one small step together.",
    todayRoutine: "Today's Routine",
    reminders: "Reminders",
    games: "Games and Activities",
    wellness: "Wellness and Exercise",
    memories: "Family Memories",
    emergency: "Emergency Assistance",
    helpMe: "Help Me",
    voiceCommand: "Voice Command",
    offlineNotice: "Working offline. Saved reminders and games are available.",
    callCaregiver: "Call Caregiver",
    done: "Done",
    remindLater: "Remind me later",
    needHelp: "I need help",
    backHome: "Back to Home",
  },
  hi: {
    languageName: "हिन्दी (Hindi)",
    appName: "सांगपा (SANGPA)",
    tagline: "छोटे कदम। सुनहरे पल।",
    caregiverBtn: "मैं एक देखभालकर्ता (केयरगिवर) हूँ",
    patientBtn: "मैं गतिविधियों और देखभाल के लिए यहाँ हूँ",
    listenInstructions: "निर्देश सुनें",
    openingInstruction: "नमस्ते! सांगपा में आपका प्यारा स्वागत है। यदि आप अपनी देखभाल, हल्की कसरत और याददाश्त के खेलों के लिए आए हैं, तो नीचे दिए गए बड़े हरे बटन को दबाएं। और यदि आप परिवार के देखभालकर्ता हैं, तो सफेद बटन दबाएं। मैं हर पल आपके साथ हूँ!",
    greeting: "नमस्ते, कमला दादी",
    whatToDo: "आज आप क्या करना चाहेंगी?",
    nextActivity: "अगला कार्य",
    drinkWater: "सुबह 10:00 बजे पानी पीना है",
    calmMessage: "आप आज बहुत अच्छा कर रही हैं। चलिए एक छोटा कदम साथ उठाते हैं।",
    todayRoutine: "आज की दिनचर्या",
    reminders: "याद दिलाने वाले संदेश (रिमाइंडर)",
    games: "खेल और गतिविधियाँ",
    wellness: "स्वास्थ्य और हल्का व्यायाम",
    memories: "पारिवारिक यादें",
    emergency: "आपातकालीन सहायता",
    helpMe: "मदद चाहिए",
    voiceCommand: "आवाज़ से बोलें",
    offlineNotice: "ऑफ़लाइन मोड। आपके सुरक्षित रिमाइंडर और खेल उपलब्ध हैं।",
    callCaregiver: "रिया को कॉल करें",
    done: "हो गया",
    remindLater: "थोड़ी देर बाद याद दिलाएं",
    needHelp: "मुझे मदद चाहिए",
    backHome: "मुख्य पृष्ठ पर जाएं",
  },
  as: {
    languageName: "অসমীয়া (Assamese)",
    appName: "চাংপা (SANGPA)",
    tagline: "ক্ষুদ্ৰ পদক্ষেপ। সোণালী মুহূৰ্ত।",
    caregiverBtn: "মই এগৰাকী যত্নকৰ্তা (কেয়াৰগিভাৰ)",
    patientBtn: "মই যত্ন আৰু কাৰ্যকলাপৰ বাবে আহিছোঁ",
    listenInstructions: "নিৰ্দেশনা শুনক",
    openingInstruction: "নমস্কাৰ! চাংপালৈ আপোনাক সাদৰ স্বাগতম জনাইছোঁ। আপুনি যদি নিজৰ যত্ন, লঘু ব্যায়াম আৰু স্মৃতিৰ খেলাৰ বাবে আহিছে, তেন্তে তলৰ ডাঙৰ সেউজীয়া বুটামটো টিপক। আৰু যদি আপুনি পৰিয়ালৰ যত্নকৰ্তা, তেন্তে বগা বুটামটো বাছক। মই আপোনাৰ লগতেই আছোঁ!",
    greeting: "নমস্কাৰ, কমলা আইতা",
    whatToDo: "আজি আপুনি কি কৰিব বিচাৰে?",
    nextActivity: "পৰৱৰ্তী কাম",
    drinkWater: "পুৱা ১০:০০ বজাত পানী খাব লাগিব",
    calmMessage: "আপুনি আজি খুবেই ভাল কৰিছে। আহক একেলগে এটা সৰু খোজ পেলাওঁ।",
    todayRoutine: "আজিৰ দিনলিপি",
    reminders: "মনত পেলোৱা সূচী",
    games: "খেলা-ধূলা আৰু ক্ৰিয়া",
    wellness: "স্বাস্থ্য আৰু শৰীৰচৰ্চা",
    memories: "পৰিয়ালৰ পুৰণি স্মৃতি",
    emergency: "জৰুৰীকালীন সহায়",
    helpMe: "সহায় লাগে",
    voiceCommand: "কথা কৈ কওক",
    offlineNotice: "অফলাইন চলি আছে। সাঁচি থোৱা সকলো কাৰ্য্য উপলব্ধ।",
    callCaregiver: "ৰিয়াক ফোন কৰক",
    done: "হৈ গ'ল",
    remindLater: "পিছত মনত পেলাব",
    needHelp: "মোক সহায় লাগে",
    backHome: "গৃহ পৃষ্ঠালৈ ঘূৰি যাওক",
  },
  bn: {
    languageName: "বাংলা (Bengali)",
    appName: "সাংপা (SANGPA)",
    tagline: "ছোট পদক্ষেপ। সুন্দর মুহূর্ত।",
    caregiverBtn: "আমি একজন যত্নকারী (কেয়ারগিভার)",
    patientBtn: "আমি যত্ন ও কার্যকলাপের জন্য এসেছি",
    listenInstructions: "নির্দেশনা শুনুন",
    openingInstruction: "নমস্কার! সাংপাতে আপনাকে অনেক ভালোবাসা ও স্বাগতম। আপনি যদি নিজের যত্ন, সহজ শরীরচর্চা ও স্মৃতি খেলার জন্য এসে থাকেন, তবে নিচের বড় সবুজ বোতামটি চাপুন। আর আপনি যদি পরিবারের যত্নকারী হন, তবে সাদা বোতামটি বেছে নিন। আমি সবসময় আপনার সাথে আছি!",
    greeting: "নমস্কার, কমলা দিদিমা",
    whatToDo: "আজ আপনি কী করতে চান?",
    nextActivity: "পরবর্তী কাজ",
    drinkWater: "সকাল ১০:০০ টায় জল খেতে হবে",
    calmMessage: "আপনি আজ খুব ভালো আছেন। আসুন একসাথে এক পা এগিয়ে যাই।",
    todayRoutine: "আজকের রুটিন",
    reminders: "স্মারক বার্তা",
    games: "মজার খেলা ও কাজ",
    wellness: "স্বাস্থ্য ও শরীরচর্চা",
    memories: "পারিবারিক স্মৃতি",
    emergency: "জরুরি সহায়তা",
    helpMe: "সাহায্য চাই",
    voiceCommand: "মুখে কথা বলুন",
    offlineNotice: "অফলাইন চলছে। সংরক্ষিত বার্তা ও খেলাগুলি তৈরি আছে।",
    callCaregiver: "রিয়াকে ফোন করুন",
    done: "হয়ে গেছে",
    remindLater: "পরে মনে করিয়ে দাও",
    needHelp: "সাহায্য চাই",
    backHome: "প্রধান পাতায় ফিরুন",
  },
  mni: {
    languageName: "মৈতৈলোন্ (Manipuri)",
    appName: "সাংপা (SANGPA)",
    tagline: "অপিকপা খোঙথাং। চাউরবা তানফম।",
    caregiverBtn: "ঐহাক য়েংশিনবীরিবা অমনি (কেয়ারগিভার)",
    patientBtn: "ঐহাক য়েংশিনবা অমসুং থবকশিংগীদমক লৈজরি",
    listenInstructions: "পাউতাক তাগদবনি",
    openingInstruction: "খুরুমজরি! সাংপাদা তরাম্না ওকচরি। অদোম নুমিৎ খুদিংগী য়েংশিনবা, অরোইবা এক্সারসাইজ অমসুং নীংশিংবগী শান্ন-খোৎনবগীদমক লাকপীরবদি, মখাগী অশেংবা অচৌবা অতেনবা বটনদু নম্বীয়ু। অদোম য়ুমগী য়েংশিনবীরিবা মী ওইরবদি, অঙৌবা বটনদু খনবীয়ু। ঐহাক অদোমগা লোয়ননা লৈজরি!",
    greeting: "খুরুমজরি, কমলা ইবেম্মা",
    whatToDo: "ঙসি অদোম করি তৌবা পাম্বীগে?",
    nextActivity: "মথংগী থবক",
    drinkWater: "অয়ুক পুং ১০:০০ দা ঈশিং থকপীবগী মতম",
    calmMessage: "অদোম ঙসি য়াম্না ফনা লৈরি। ঐখোয় পুন্না অপিকপা খোঙথাং অমা থাংগদবনি।",
    todayRoutine: "ঙসিগী থবকশিং",
    reminders: "নীংশিংহন্নবা পাউদম",
    games: "শান্ন-খোৎনবা অমসুং থবকশিং",
    wellness: "হকচাংগী হকশেল অমসুং এক্সারসাইজ",
    memories: "ইমুংগী নীংশিংবা",
    emergency: "অচৌবা মতেং (ইমার্জেন্সি)",
    helpMe: "মতেং পাংবীয়ু",
    voiceCommand: "খোনথোক্না হায়বীয়ু",
    offlineNotice: "ওফলাইন ওইনা চৎথরি। থমখিবা নীংশিংহন্নবা অমসুং শান্নবশিং শেম-শাদুনা লৈরে।",
    callCaregiver: "রিয়াদা ফোন তৌবীয়ু",
    done: "লোইরে",
    remindLater: "মতংদা অমুক নীংশিংহন্বীখ্রনু",
    needHelp: "ঐহাক মতেং মথৌ তারি",
    backHome: "অহানবা লমায়দা চৎলু",
  },
  nag: {
    languageName: "Nagamese (নাগামিজ)",
    appName: "SANGPA",
    tagline: "Choto khujli. Bhal homoy.",
    caregiverBtn: "Moi ekta caregiver asey",
    patientBtn: "Moi care aru activities nimite ahese",
    listenInstructions: "Instructions hunibi",
    openingInstruction: "Namaste! SANGPA te apuni ke bhal purna swagat asey! Apuni nijor bhal thakibole, gentle exercises aru memory games kheli bole aheise koile, niche laga daanghor green button te dababi. Aru apuni family caregiver asey koile, white button te click koribi. Moi apuni logot te asey!",
    greeting: "Namaste, Kamala Dadi",
    whatToDo: "Aji apuni ki koribole mon asey?",
    nextActivity: "Next Activity",
    drinkWater: "Rati poa 10:00 AM te paani khabole lage",
    calmMessage: "Apuni aji bhal korise. Ahibi ekta choto step loi lohi.",
    todayRoutine: "Aji laga Routine",
    reminders: "Yaad kora Reminders",
    games: "Khel aru Activities",
    wellness: "Wellness aru Exercise",
    memories: "Family Memories",
    emergency: "Emergency Help",
    helpMe: "Moi ke Help Lage",
    voiceCommand: "Awaaz te Kotha Kobi",
    offlineNotice: "Offline cholise. Saved reminders aru games asey.",
    callCaregiver: "Riya ke Phone Kori",
    done: "Hoise",
    remindLater: "Pichite yaad korabi",
    needHelp: "Moi help lage",
    backHome: "Home te jabi",
  },
  es: {
    languageName: "Español (Spanish)",
    appName: "SANGPA",
    tagline: "Pequeños pasos. Grandes momentos.",
    caregiverBtn: "Soy un cuidador",
    patientBtn: "Estoy aquí para actividades y cuidados",
    listenInstructions: "Escuchar instrucciones",
    openingInstruction: "¡Bienvenida a SANGPA! Si está aquí para su cuidado diario, ejercicios suaves y divertidos juegos de memoria, presione el botón verde grande abajo. Si es un cuidador familiar, presione el botón blanco. ¡Estoy aquí con usted!",
    greeting: "Hola, Kamala Dadi",
    whatToDo: "¿Qué le gustaría hacer hoy?",
    nextActivity: "Próxima actividad",
    drinkWater: "Beber agua a las 10:00 AM",
    calmMessage: "Lo está haciendo muy bien hoy. Demos un pequeño paso juntos.",
    todayRoutine: "Rutina de hoy",
    reminders: "Recordatorios",
    games: "Juegos y actividades",
    wellness: "Bienestar y ejercicios",
    memories: "Recuerdos familiares",
    emergency: "Asistencia de emergencia",
    helpMe: "Necesito ayuda",
    voiceCommand: "Comando de voz",
    offlineNotice: "Trabajando sin conexión. Recordatorios y juegos disponibles.",
    callCaregiver: "Llamar a Riya",
    done: "Listo",
    remindLater: "Recordar más tarde",
    needHelp: "Necesito ayuda",
    backHome: "Volver al inicio",
  }
};

export const initialPatientProfile: PatientProfile = {
  name: "Maya Devi",
  preferredName: "Kamala Dadi",
  age: 74,
  condition: "Mild Cognitive Impairment (MCI) - Stage 2",
  avatar: "/assets/patient_avatar.jpg",
  language: "en",
  reminderSound: "temple_bell",
  communicationPref: "combined",
  quietHours: {
    enabled: true,
    start: "21:30",
    end: "07:00",
    bypassForEmergency: true
  },
  battery: 86,
  lastActive: "Today, 10:42 AM",
  isOnline: true
};

export const initialReminders: ReminderItem[] = [
  {
    id: "rem-1",
    title: "Morning Blood Pressure Medicine",
    time: "08:30 AM",
    category: "medicine",
    status: "completed",
    icon: "Pill",
    dosage: "Amlodipine 5mg (1 white tablet)",
    instructions: "Take with half a glass of warm water after breakfast.",
    audioText: "Kamala Dadi, it is time for your morning blood pressure tablet with warm water.",
    isOffline: true,
    notifyCaregiverIfMissed: true,
    scheduledTime: "08:30"
  },
  {
    id: "rem-2",
    title: "Drink Pure Fresh Water",
    time: "10:00 AM",
    category: "hydration",
    status: "upcoming",
    icon: "Droplets",
    dosage: "1 Full Glass (250ml)",
    instructions: "Sip slowly while sitting comfortably.",
    audioText: "It is time to drink a glass of refreshing water. Let us hydrate together.",
    isOffline: true,
    notifyCaregiverIfMissed: false,
    scheduledTime: "10:00"
  },
  {
    id: "rem-3",
    title: "Post-Lunch Memory Vitamin B-Complex",
    time: "01:30 PM",
    category: "medicine",
    status: "upcoming",
    icon: "Pill",
    dosage: "Neuro-B Capsule (1 yellow capsule)",
    instructions: "Take 15 minutes after lunch with warm milk or water.",
    audioText: "Time for your post-lunch memory vitamin. Would you like me to guide you?",
    isOffline: true,
    notifyCaregiverIfMissed: true,
    scheduledTime: "13:30"
  },
  {
    id: "rem-4",
    title: "Afternoon Herbal Chamomile Tea",
    time: "04:30 PM",
    category: "hydration",
    status: "upcoming",
    icon: "CupSoda",
    dosage: "Warm soothing cup",
    instructions: "Enjoy a warm cup in the garden or balcony.",
    audioText: "Afternoon tea time. A relaxing chamomile cup will feel wonderful.",
    isOffline: true,
    notifyCaregiverIfMissed: false,
    scheduledTime: "16:30"
  },
  {
    id: "rem-5",
    title: "Evening Balcony Walk with Riya",
    time: "05:45 PM",
    category: "exercise",
    status: "upcoming",
    icon: "Footprints",
    dosage: "15-20 minutes slow stroll",
    instructions: "Wear comfortable soft slippers and hold Riya's arm.",
    audioText: "Riya is ready to walk with you on the balcony and watch the sunset.",
    isOffline: true,
    notifyCaregiverIfMissed: false,
    scheduledTime: "17:45"
  },
  {
    id: "rem-6",
    title: "Night Medicine with Warm Milk",
    time: "08:45 PM",
    category: "medicine",
    status: "upcoming",
    icon: "Moon",
    dosage: "Sleep Aid & Calcium (1 tablet)",
    instructions: "Drink with warm turmeric milk before listening to bedtime melody.",
    audioText: "Time for your night medicine and warm turmeric milk before peaceful sleep.",
    isOffline: true,
    notifyCaregiverIfMissed: true,
    scheduledTime: "20:45"
  }
];

export const initialDailyActivities: DailyActivity[] = [
  {
    id: "act-1",
    title: "Morning Sunshine & Deep Breathing",
    time: "07:30 AM",
    shortInstruction: "Sit near the open veranda window and take 5 slow breaths.",
    icon: "Sun",
    completed: true,
    isCurrent: false,
    category: "wellness",
    audioText: "Gentle morning sunshine helps keep our rhythm calm and refreshed."
  },
  {
    id: "act-2",
    title: "Nutritious Breakfast",
    time: "08:00 AM",
    shortInstruction: "Warm oats porridge with chopped almonds and honey.",
    icon: "Utensils",
    completed: true,
    isCurrent: false,
    category: "meal",
    audioText: "Breakfast complete. You enjoyed your porridge with almonds."
  },
  {
    id: "act-3",
    title: "Morning Blood Pressure Tablet",
    time: "08:30 AM",
    shortInstruction: "Take 1 Amlodipine tablet with water.",
    icon: "Pill",
    completed: true,
    isCurrent: false,
    category: "medicine",
    audioText: "Medicine taken on time. Very well done."
  },
  {
    id: "act-4",
    title: "Mid-Morning Hydration",
    time: "10:00 AM",
    shortInstruction: "Drink 1 glass of fresh room-temperature water.",
    icon: "Droplets",
    completed: true,
    isCurrent: false,
    category: "hydration",
    audioText: "Drinking water keeps your mind clear and energised."
  },
  {
    id: "act-5",
    title: "Gentle Hand & Shoulder Stretching",
    time: "10:30 AM",
    shortInstruction: "Follow SANGPA's 5 seated arm stretches.",
    icon: "Activity",
    completed: true,
    isCurrent: false,
    category: "exercise",
    audioText: "A few seated arm raises and shoulder rolls to keep joints supple."
  },
  {
    id: "act-6",
    title: "Cognitive Sequence Recall Game",
    time: "11:15 AM",
    shortInstruction: "Recall a playful pattern of traditional clay pots and flowers.",
    icon: "Sparkles",
    completed: true,
    isCurrent: false,
    category: "game",
    audioText: "Let us exercise our memory with a pleasant 3-step sequence."
  },
  {
    id: "act-7",
    title: "MIND-Diet Lunch (Khichdi & Spinach)",
    time: "12:45 PM",
    shortInstruction: "Moong dal khichdi enriched with walnuts and spinach puree.",
    icon: "Utensils",
    completed: true,
    isCurrent: false,
    category: "meal",
    audioText: "Lunch prepared by Riya, packed with omega-3 and brain vitamins."
  },
  {
    id: "act-8",
    title: "Rest & Afternoon Siesta",
    time: "02:00 PM",
    shortInstruction: "Rest in bed with soft instrumental flute music.",
    icon: "Bed",
    completed: true,
    isCurrent: false,
    category: "rest",
    audioText: "Quiet resting time. SANGPA will mute non-urgent chimes."
  },
  {
    id: "act-9",
    title: "Afternoon Herbal Chamomile Tea",
    time: "04:30 PM",
    shortInstruction: "Enjoy a warm soothing cup in the garden or balcony.",
    icon: "Droplets",
    completed: true,
    isCurrent: false,
    category: "hydration",
    audioText: "Afternoon tea time. A relaxing chamomile cup will feel wonderful."
  },
  {
    id: "act-10",
    title: "Evening Balcony Walk with Riya",
    time: "05:45 PM",
    shortInstruction: "Wear comfortable slippers and take a gentle 15-minute stroll.",
    icon: "Activity",
    completed: true,
    isCurrent: false,
    category: "exercise",
    audioText: "Riya is ready to walk with you on the balcony and watch the sunset."
  },
  {
    id: "act-11",
    title: "Light Dinner & Family Conversation",
    time: "07:30 PM",
    shortInstruction: "Warm roti, steamed vegetables, and pleasant chat with Aarav.",
    icon: "Utensils",
    completed: true,
    isCurrent: false,
    category: "meal",
    audioText: "Dinner time. Enjoy warm wholesome food with your loving family."
  },
  {
    id: "act-12",
    title: "Night Medicine with Warm Turmeric Milk",
    time: "08:45 PM",
    shortInstruction: "Take evening sleep aid and calcium tablet with warm milk.",
    icon: "Pill",
    completed: false,
    isCurrent: false,
    category: "medicine",
    audioText: "Time for your night medicine and warm turmeric milk before peaceful sleep."
  },
  {
    id: "act-13",
    title: "Bedtime Gratitude & Calming Music",
    time: "09:45 PM",
    shortInstruction: "Lie down comfortably and listen to peaceful instrumental melody.",
    icon: "Bed",
    completed: false,
    isCurrent: true,
    category: "rest",
    audioText: "Time to rest peacefully, Kamala Dadi. You had a wonderful day."
  }
];

export const initialGames: CognitiveGame[] = [
  {
    id: "sequence",
    title: "Sequence Recall",
    titleHi: "क्रम याद रखें",
    description: "Watch or listen to a sequence of cultural symbols and reproduce it.",
    icon: "ListOrdered",
    category: "cognitive",
    difficultyLevel: 2,
    accuracy: 88,
    streak: 4,
    lastPlayed: "Yesterday",
    isCaregiverRecommended: true,
    offlineReady: true
  },
  {
    id: "rhythm",
    title: "Rhythm Tapping",
    titleHi: "लयबद्ध थाप (Rhythm)",
    description: "Tap gently along to a calm rhythm: Tap, Tap, Pause, Tap.",
    icon: "Music",
    category: "cognitive",
    difficultyLevel: 1,
    accuracy: 94,
    streak: 6,
    lastPlayed: "Today, 9:15 AM",
    isCaregiverRecommended: true,
    offlineReady: true
  },
  {
    id: "flashcards",
    title: "Family & Loved Ones Flashcards",
    titleHi: "पारिवारिक फ़्लैशकार्ड्स",
    description: "Look at family photos, recall their names, and hear their voices.",
    icon: "Image",
    category: "cognitive",
    difficultyLevel: 2,
    accuracy: 90,
    streak: 5,
    lastPlayed: "2 days ago",
    isCaregiverRecommended: true,
    offlineReady: true
  },
  {
    id: "sorting",
    title: "Culturally Familiar Object Sorting",
    titleHi: "वस्तु वर्गीकरण",
    description: "Group familiar items into Fruits, Festival items, and Daily tools.",
    icon: "Boxes",
    category: "cognitive",
    difficultyLevel: 2,
    accuracy: 82,
    streak: 3,
    lastPlayed: "3 days ago",
    isCaregiverRecommended: false,
    offlineReady: true
  },
  {
    id: "dice_category",
    title: "Dice Math Journey",
    titleHi: "पासा गणित यात्रा",
    description: "Roll digital dice for gentle counting, adding numbers, and solving familiar food & shop math.",
    icon: "Dices",
    category: "cognitive",
    difficultyLevel: 1,
    accuracy: 96,
    streak: 7,
    lastPlayed: "Today",
    isCaregiverRecommended: true,
    offlineReady: true
  },
  {
    id: "dice_movement",
    title: "Dice & Movement (With Caregiver)",
    titleHi: "पासा और हल्का व्यायाम",
    description: "Roll for gentle physical actions: Hand claps, deep breath, gentle shoulder roll.",
    icon: "HeartHandshake",
    category: "physical",
    difficultyLevel: 1,
    accuracy: 100,
    streak: 8,
    lastPlayed: "Yesterday",
    isCaregiverRecommended: true,
    offlineReady: true
  }
];

export const initialMemories: MemoryItem[] = [
  {
    id: "mem-1",
    title: "Riya & Family Study Gathering",
    relationship: "Eldest Daughter",
    caption: "Riya studying together with cousins and loved ones in the peaceful courtyard with notebooks and laptop.",
    audioNote: "Kamala Dadi, remember watching Riya and the young ones learning together under the warm sun?",
    imageUrl: "/assets/memory_1.jpg",
    dateOrEra: "College Years",
    location: "Courtyard Verandah",
    isFavorite: true,
    inFlashcards: true
  },
  {
    id: "mem-2",
    title: "Little Grandson Aarav's 5th Birthday",
    relationship: "Grandson (Riya's Son)",
    caption: "Aarav smiling before his 5th birthday cake with candle '5' in the courtyard, with Dadi, Riya, and all cousins clapping joyfully.",
    audioNote: "Kamala Dadi, remember little Aarav's joyful 5th birthday celebration in the courtyard?",
    imageUrl: "/assets/memory_aarav_birthday.jpg",
    dateOrEra: "5th Birthday",
    location: "Courtyard Verandah",
    isFavorite: true,
    inFlashcards: true
  },
  {
    id: "mem-4",
    title: "Assam Diwali & Evening Diya Lighting",
    relationship: "Family Festival",
    caption: "Lighting the sacred earthen saki (diya) at dusk in Assam, welcoming blessings of light, peace, and prosperity into our home.",
    audioNote: "Lighting the sacred earthen saki at dusk in Assam, welcoming peace, good health, and prosperity.",
    imageUrl: "/assets/memory_diwali_assam.jpg",
    dateOrEra: "Diwali / Kati Bihu",
    location: "Assam Courtyard",
    isFavorite: true,
    inFlashcards: true
  }
];

export const initialAlerts: CaregiverAlert[] = [
  {
    id: "alt-1",
    timestamp: "10:18 AM",
    type: "missed_hydration",
    severity: "needs_attention",
    title: "10:00 AM Water Reminder Pending",
    description: "Kamala Dadi has not confirmed her morning glass of water after 18 minutes.",
    recommendedAction: "Offer a warm glass of water or send a friendly voice nudge through SANGPA.",
    resolved: false
  },
  {
    id: "alt-2",
    timestamp: "Yesterday, 06:30 PM",
    type: "appointment",
    severity: "info",
    title: "Upcoming Neurologist Checkup",
    description: "Dr. Anita Verma consultation scheduled for Friday, 11:00 AM at Apollo Geriatric Clinic.",
    recommendedAction: "Confirm driver arrival and carry recent blood pressure log.",
    resolved: false
  },
  {
    id: "alt-3",
    timestamp: "2 days ago",
    type: "missed_medicine",
    severity: "urgent",
    title: "Evening Tablet Snoozed Twice",
    description: "Evening vitamin was snoozed twice before being confirmed at 07:15 PM.",
    recommendedAction: "Verify with visiting nurse Preeti whether stomach discomfort caused delay.",
    resolved: true
  }
];

export const initialContacts: ContactItem[] = [
  {
    id: "cnt-1",
    name: "Riya Sharma",
    relation: "Daughter (Primary Caregiver)",
    phone: "+91 98765 43210",
    role: "caregiver",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    canCallInEmergency: true,
    receivesAlerts: true,
    isPrimary: true
  },
  {
    id: "cnt-2",
    name: "Amit Sharma",
    relation: "Son (Lives nearby)",
    phone: "+91 98765 43211",
    role: "family",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    canCallInEmergency: true,
    receivesAlerts: true,
    isPrimary: false
  },
  {
    id: "cnt-3",
    name: "Dr. Anita Verma",
    relation: "Neurologist & Geriatrician",
    phone: "+91 98765 12345",
    role: "doctor",
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80",
    canCallInEmergency: true,
    receivesAlerts: false,
    isPrimary: false
  },
  {
    id: "cnt-4",
    name: "Preeti Das",
    relation: "Visiting Home Nurse",
    phone: "+91 98765 67890",
    role: "caregiver",
    avatar: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=150&auto=format&fit=crop&q=80",
    canCallInEmergency: false,
    receivesAlerts: true,
    isPrimary: false
  },
  {
    id: "cnt-5",
    name: "National Emergency Ambulance",
    relation: "Emergency Service 108 / 112",
    phone: "108",
    role: "emergency",
    avatar: "",
    canCallInEmergency: true,
    receivesAlerts: false,
    isPrimary: false
  }
];
